## Session 2: 初步理解机器学习 (Get some intuitions about Machine Learning by creating a linear regression model)

___

### What is linear regression? (什么是线性回归)

1. 数学概率
2. 一种算法

___

### How we supposed to learn it? (我们应该怎样去学习它呢)

1. Learn by example
2. Learn by experiment

___

### So the first package you should use is `scikit-learn`

> Scikit-learn is a free software machine learning library for the Python programming language.

    1. It is easy for use
    2. It has a good community

___

### Import your first ML package (导入你的第一个机器学习包)

In [4]:
from sklearn import linear_model

In [5]:
model = linear_model.LinearRegression()

In [8]:
model.fit([ [0, 0], [1, 1], [2, 2] ], 
          [   0,       1,      2   ])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
model.predict([ [3, 3], [55, 55] ])

array([ 3., 55.])

___

### One more example

In [19]:
from sklearn import linear_model

model = linear_model.LinearRegression()
model.fit([[1], [2], [3], [4], [7]],
          [ 2,   4,   9,   16,  49])
model.predict([[5], [6]])

array([28.98113208, 37.09433962])

___

### One more example

In [21]:
from sklearn import linear_model

model = linear_model.LinearRegression()
model.fit([[1,2,3], [2,3,4], [3,10,1], [8,9,4], [7,4,3]],
          [   6,       9,       14,       21,      14])
model.predict([[5, 1, 2]])

array([8.])

___

### Convert sklearn model to keras

1. find problem
2. serach that problem
3. find solution

In [220]:
from keras.models import Sequential

model = Sequential()

In [221]:
from keras.layers import Dense

model.add(Dense(units=2, activation='relu', input_dim=2))
model.add(Dense(units=1))

model.compile(loss='mean_squared_error',
              optimizer='sgd',
              metrics=['accuracy'])

In [222]:
import numpy

x = [[1,1], [2,2], [1,2], [4,3], [1,4]]
y = [ [2] ,  [4]  , [3], [7], [5]]

x = numpy.array(x)
y = numpy.array(y)

model.fit(x, y, epochs=10, batch_size=1)

Epoch 1/10
5/5 [==============================] - 1s 145ms/step - loss: 28.5372 - acc: 0.0000e+00
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 16.0311 - acc: 0.0000e+00
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 13.3427 - acc: 0.0000e+00
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 11.2660 - acc: 0.0000e+00
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 9.5507 - acc: 0.2000 
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 8.0622 - acc: 0.2000
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 6.8147 - acc: 0.2000
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 5.8422 - acc: 0.4000
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 5.1508 - acc: 0.4000
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 4.6979 - acc: 0.4000


In [223]:
inputs = numpy.array([[2,1]])
model.predict(inputs)

array([[2.5749485]], dtype=float32)